# Nombre de tu aplicación
spring.application.name=backend

# Configuración de la Base de Datos
# Usamos variables de entorno con fallback a localhost:3307 para cuando corras en el IDE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/sandbox_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# Estrategia Code-First de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Exponer los endpoints de Actuator para telemetría base de la JVM/CPU
management.endpoints.web.exposure.include=health,info,metrics

# --- ARREGLO CRÍTICO AQUÍ ---
# URLs internas para comunicarse con los contenedores de las réplicas.
# Leemos las variables REPLICA_ONE_URL y REPLICA_TWO_URL del docker-compose.
# Si no existen (corriendo en el IDE), usamos el fallback a localhost:8082/8083.
cluster.replicas.urls=${REPLICA_ONE_URL:http://localhost:8082},${REPLICA_TWO_URL:http://localhost:8083}

# Ruta dinámica donde este nodo escribirá los ficheros que reciba
cluster.storage.path=${STORAGE_PATH:/monitored/ingest}

docker.host=unix:///var/run/docker.sock